using System.IO.Compression;
using Nightfall.Infrastructure.Agora;

namespace Nightfall.Tests;

// Golden values generated by compiling and running Agora's own MIT-licensed reference
// implementation (github.com/AgoraIO/Tools, DynamicKey/AgoraDynamicKey/csharp) with these exact
// inputs and a fixed issueTs/salt (normally random/time-based — overridden via the reference's
// public _issueTs/_salt fields for reproducibility).
//
// We compare *decompressed* content, not the final base64 token string: the reference uses
// SharpZipLib's DeflaterOutputStream while this port uses System.IO.Compression.ZLibStream.
// Both produce valid, mutually-decompressible zlib streams (confirmed separately), but two
// different DEFLATE encoders aren't guaranteed to emit byte-identical compressed output for the
// same input even at "equivalent" levels — that's an encoder implementation detail Agora's
// server doesn't care about. What must match byte-for-byte is the pre-compression content
// (signature + header), since that's what actually gets parsed and HMAC-verified server-side.
public class AgoraAccessToken2Tests
{
    private const string AppId = "0123456789abcdef0123456789abcdef";
    private const string AppCertificate = "fedcba9876543210fedcba9876543210";
    private const string Channel = "nightfall-game-42";
    private const uint Uid = 12345;
    private const uint TokenExpire = 3600;
    private const uint PrivilegeExpire = 3600;
    private const uint IssueTs = 1735689600;
    private const uint Salt = 424242;

    // Captured by decompressing the reference implementation's own output (ZLibStream can
    // decompress SharpZipLib's zlib stream, proving format compatibility) for these exact inputs.
    private const string ExpectedPublisherContentHex =
        "2000CCF0AE0F71A5034234EE6A1405F4A5506BC95DEA4FA3E1BF0B6C090CC81728632000303132333435363738396162636465663031323334353637383961626364656680857467100E0000327906000100010004000100100E00000200100E00000300100E00000400100E000011006E6967687466616C6C2D67616D652D343205003132333435";

    private static byte[] DecompressToken(string token)
    {
        byte[] compressed = Convert.FromBase64String(token.Substring(3));
        using var input = new MemoryStream(compressed);
        using var zlib = new ZLibStream(input, CompressionMode.Decompress);
        using var output = new MemoryStream();
        zlib.CopyTo(output);
        return output.ToArray();
    }

    [Fact]
    public void BuildRtcToken_Publisher_DecompressedContentMatchesAgoraReferenceImplementation()
    {
        string token = AgoraAccessToken2.BuildRtcToken(
            AppId, AppCertificate, Channel, Uid, AgoraRtcRole.Publisher,
            TokenExpire, PrivilegeExpire, IssueTs, Salt);

        string actualHex = Convert.ToHexString(DecompressToken(token));

        Assert.Equal(ExpectedPublisherContentHex, actualHex);
    }

    [Fact]
    public void BuildRtcToken_ProducesAValidZlibStream_DecompressableByReferencesCompressionFormat()
    {
        // Round-trips through this port's own compress+decompress to guard against a
        // ZLibStream misuse (e.g. wrong CompressionMode) breaking the wire format itself.
        string token = AgoraAccessToken2.BuildRtcToken(
            AppId, AppCertificate, Channel, Uid, AgoraRtcRole.Subscriber,
            TokenExpire, PrivilegeExpire, IssueTs, Salt);

        var exception = Record.Exception(() => DecompressToken(token));

        Assert.Null(exception);
    }

    [Fact]
    public void BuildRtcToken_DifferentSalt_ProducesDifferentToken()
    {
        string token1 = AgoraAccessToken2.BuildRtcToken(AppId, AppCertificate, Channel, Uid, AgoraRtcRole.Publisher, TokenExpire, PrivilegeExpire, IssueTs, Salt);
        string token2 = AgoraAccessToken2.BuildRtcToken(AppId, AppCertificate, Channel, Uid, AgoraRtcRole.Publisher, TokenExpire, PrivilegeExpire, IssueTs, salt: Salt + 1);

        Assert.NotEqual(token1, token2);
    }

    [Fact]
    public void BuildRtcToken_UidZero_OmitsUidFromToken()
    {
        // uid == 0 means "don't authenticate uid, any client uid may join" -> encoded as empty string.
        var exception = Record.Exception(() =>
            AgoraAccessToken2.BuildRtcToken(AppId, AppCertificate, Channel, uid: 0, AgoraRtcRole.Publisher, TokenExpire, PrivilegeExpire, IssueTs, Salt));

        Assert.Null(exception);
    }

    [Theory]
    [InlineData("tooshort")]
    [InlineData("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz")] // 32 chars but not valid hex
    public void BuildRtcToken_InvalidAppId_Throws(string invalidAppId)
    {
        Assert.Throws<ArgumentException>(() =>
            AgoraAccessToken2.BuildRtcToken(invalidAppId, AppCertificate, Channel, Uid, AgoraRtcRole.Publisher, TokenExpire, PrivilegeExpire, IssueTs, Salt));
    }
}
