import { useCallback, useEffect, useState } from "react";
import { adminApi } from "./adminApi";
import "./admin.css";
import "./admin-live.css";

type Settings={version:number;minPlayers:number;maxPlayers:number;maintenanceMode:boolean;maintenanceMessage:string;enabledCommands:string[];soloTestEnabled:boolean;miniAppBaseUrl:string;helpMessage:string;welcomeMessage:string;updatedAt:string};
const nav=["overview","live-games","history","players","chats","events","health","settings"];
const labels:Record<string,string>={overview:"Overview","live-games":"Live games",history:"Game history",players:"Players",chats:"Chats",events:"Events & audit",health:"Service health",settings:"Bot settings"};

function Login({onLogin}:{onLogin:()=>void}) { const [username,setUsername]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);return <main className="admin-login"><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await adminApi.login(username,password);await adminApi.csrf();onLogin();}catch(x){setError(x instanceof Error?x.message:"Login failed");}finally{setBusy(false)}}}><div className="admin-brand"><span>◐</span><div><b>Nightfall</b><small>Command Center</small></div></div><h1>Welcome back</h1><p>Sign in to manage your bot and games.</p><label>Username<input autoFocus value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="admin-error">{error}</div>}<button disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form></main> }

function JsonTable({items}:{items:Record<string,unknown>[]}) { if(!items.length)return <div className="admin-empty">No records found</div>;const keys=Object.keys(items[0]).filter(k=>!Array.isArray(items[0][k])&&typeof items[0][k]!=="object").slice(0,7);return <div className="table-wrap"><table><thead><tr>{keys.map(k=><th key={k}>{k.replace(/([A-Z])/g," $1")}</th>)}</tr></thead><tbody>{items.map((item,i)=><tr key={i}>{keys.map(k=><td key={k}>{typeof item[k]==="boolean"?(item[k]?"Yes":"No"):String(item[k]??"—")}</td>)}</tr>)}</tbody></table></div> }

function DataPage({page}:{page:string}) { const[load,setLoad]=useState(true),[error,setError]=useState(""),[data,setData]=useState<Record<string,unknown>>({}),[revision,setRevision]=useState(0);const endpoint=page==="live-games"?"/games?status=active":page==="history"?"/games?status=history":`/${page}`;useEffect(()=>{setLoad(true);adminApi.get<Record<string,unknown>>(endpoint).then(setData).catch(e=>setError(e.message)).finally(()=>setLoad(false))},[endpoint,revision]);if(load)return <div className="admin-loading">Loading {labels[page].toLowerCase()}...</div>;if(error)return <div className="admin-error">{error}</div>;if(page==="overview") {const cards:[string,unknown][]=[['Active games',data.activeGames],['Completed',data.completedGames],['Cancelled',data.cancelledGames],['Players',data.users],['Chats',data.chats]];return <><div className="metric-grid">{cards.map(([l,v])=><article className="metric" key={l}><span>{l}</span><strong>{String(v??0)}</strong><small>All time</small></article>)}</div><section className="panel"><h2>Recent activity</h2><JsonTable items={(data.recentEvents??[]) as Record<string,unknown>[]}/></section></>};if(page==="health"){return <div className="health-grid">{Object.entries(data).filter(([k])=>k!=="botHeartbeat").map(([k,v])=><article className="health-card" key={k}><i className={v==="healthy"?"ok":"warn"}/><div><b>{k}</b><span>{String(v)}</span></div></article>)}</div>};if(page==="live-games"){const games=(data.items??[]) as Record<string,unknown>[];return <div className="live-grid">{games.length===0?<div className="admin-empty panel">No live games</div>:games.map(g=><section className="panel live-card" key={String(g.gameId)}><div className="panel-title"><div><small>{String(g.gameId)}</small><h2>{String(g.currentPhase)} · Night {String(g.nightNumber)}</h2></div><button className="danger" onClick={async()=>{const reason=prompt("Enter the cancellation reason:");if(reason&&confirm("Cancel this game? This cannot be undone.")){await adminApi.post(`/games/${g.gameId}/cancel`,{reason});setRevision(x=>x+1)}}}>Cancel game</button></div><details><summary>Inspect full game state</summary><pre>{JSON.stringify(g,null,2)}</pre></details></section>)}</div>};return <section className="panel"><div className="panel-title"><h2>{labels[page]}</h2><span>{String(data.total??0)} records</span></div><JsonTable items={(data.items??[]) as Record<string,unknown>[]}/></section> }

function SettingsPage(){const[s,setS]=useState<Settings|null>(null),[original,setOriginal]=useState(""),[message,setMessage]=useState("");useEffect(()=>{adminApi.get<Settings>("/settings").then(x=>{setS(x);setOriginal(JSON.stringify(x))})},[]);if(!s)return <div className="admin-loading">Loading settings…</div>;const changed=JSON.stringify(s)!==original;const set=<K extends keyof Settings>(k:K,v:Settings[K])=>setS({...s,[k]:v});return <form className="settings" onSubmit={async e=>{e.preventDefault();try{const saved=await adminApi.put<Settings>("/settings",s);setS(saved);setOriginal(JSON.stringify(saved));setMessage("Settings saved. Bot behavior will refresh within seconds.")}catch(x){setMessage(x instanceof Error?x.message:"Save failed")}}}><section className="panel"><h2>Gameplay</h2><p className="hint">Limits are snapshotted for newly created games. Active games will not change.</p><div className="field-row"><label>Minimum players<input type="number" min="2" max="50" value={s.minPlayers} onChange={e=>set("minPlayers",+e.target.value)}/></label><label>Maximum players<input type="number" min="2" max="50" value={s.maxPlayers} onChange={e=>set("maxPlayers",+e.target.value)}/></label></div></section><section className="panel"><h2>Bot behavior</h2><label className="toggle"><input type="checkbox" checked={s.maintenanceMode} onChange={e=>set("maintenanceMode",e.target.checked)}/><span/>Maintenance mode</label><label>Maintenance message<textarea value={s.maintenanceMessage} onChange={e=>set("maintenanceMessage",e.target.value)}/></label><label className="toggle"><input type="checkbox" checked={s.soloTestEnabled} onChange={e=>set("soloTestEnabled",e.target.checked)}/><span/>Enable solo testing</label><label>Mini-app base URL<input value={s.miniAppBaseUrl} onChange={e=>set("miniAppBaseUrl",e.target.value)} placeholder="https://t.me/YourBot/app"/></label></section><section className="panel"><h2>Commands</h2><div className="commands">{s.enabledCommands.concat(["newgame","join","startgame","resolvenight","startvoting","resolvevoting","startnight","myrole","solotest","solonext","help","start"].filter(x=>!s.enabledCommands.includes(x))).map(c=><label className="toggle" key={c}><input type="checkbox" checked={s.enabledCommands.includes(c)} onChange={e=>set("enabledCommands",e.target.checked?[...s.enabledCommands,c]:s.enabledCommands.filter(x=>x!==c))}/><span/>/{c}</label>)}</div></section><section className="panel"><h2>Messages</h2><label>Welcome announcement<textarea rows={4} value={s.welcomeMessage} onChange={e=>set("welcomeMessage",e.target.value)}/><small>Use {'{creator}'} to insert the game creator.</small></label><label>Help response<textarea rows={8} value={s.helpMessage} onChange={e=>set("helpMessage",e.target.value)}/></label></section><div className="savebar"><span>{message||`${changed?"Unsaved changes":"All changes saved"} · Version ${s.version}`}</span><button disabled={!changed}>Save settings</button></div></form>}

export default function AdminApp(){const[auth,setAuth]=useState<boolean|null>(null);const[page,setPage]=useState(location.pathname.split('/')[2]||"overview");const check=useCallback(()=>adminApi.session().then(async()=>{await adminApi.csrf();setAuth(true)}).catch(()=>setAuth(false)),[]);useEffect(()=>{check()},[check]);useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(document.querySelector('.savebar button:not(:disabled)'))e.preventDefault()};addEventListener('beforeunload',warn);return()=>removeEventListener('beforeunload',warn)},[]);if(auth===null)return <div className="admin-loading fullscreen">Opening command center…</div>;if(!auth)return <Login onLogin={()=>setAuth(true)}/>;const go=(p:string)=>{history.pushState({},"",`/admin/${p}`);setPage(p)};return <div className="admin-shell"><aside><div className="admin-brand"><span>◐</span><div><b>Nightfall</b><small>Command Center</small></div></div><nav>{nav.map(n=><button className={page===n?"active":""} key={n} onClick={()=>go(n)}><i>{n==="overview"?"⌂":n==="settings"?"⚙":"◇"}</i>{labels[n]}</button>)}</nav><button className="logout" onClick={async()=>{await adminApi.logout();setAuth(false)}}>Sign out</button></aside><main><header><div><small>ADMIN CONSOLE</small><h1>{labels[page]??"Dashboard"}</h1></div><div className="status"><i/> Bot connected</div></header><div className="admin-content">{page==="settings"?<SettingsPage/>:<DataPage page={page}/>}</div></main></div>}
